### PR TITLE
Edit the readme with right example

### PR DESCRIPTION
**Pull request by Logan1x**
Fixes for #3

### CODE REVIEW

**Comment by Logan1x** [comment]
I removed your link because this was giving an error like this .
image

**Comment by geekplux** [comment]
thanks for your contributing

**Comment by Logan1x** [comment]
Thank you for making this awesome plugin. This is what I was wanted from the day I wrote my first blog post.😊

**Comment by geekplux** [comment]
@Logan1x I have read your great article! 👍

**Pull request merged**
